import pandas as pd


def cargar_variables_prototipo():
    """Carga el catalogo prototipo de variables SCADA y propiedades de materiales."""

    datos = [
        {
            "ID_Tecnico": "1GEV007CE",
            "Nombre_amigable": "potencia_activa",
            "Descripcion_funcional": "Nivel de exigencia operativa del sistema - Carga mecanica sobre el rotor",
            "Unidad": "MW",
            "Tipo_dato": "float",
            "Tipo_en_modelo": "Carga",
            "Tipo_variable": "Potencia",
            "Mecanismos_asociados": "Vibraciones_mecanicas,HCF (High Cycle Fatigue)",
            "Ecuacion": "G(X) = C - D (estado limite, Nachlas 1995)",
            "Rol_en_ecuacion": "Potencia de salida que induce esfuerzos mecanicos sobre el rotor. Participa en funcion de estado limite G(X) = Capacidad - Demanda. Referencia: Perez (2024), Nachlas (1995)",
            "Rango_min": 263.56,
            "Rango_max": 272.11,
            "Distribucion_observada": "Weibull (forma=132.4, escala=269.6), asimetrica positiva, colas largas, KS p-value=0.71",
            "Pregunta_planta": "¿Ubicacion del sensor? ¿Medicion directa o calculada? ¿Frecuencia de muestreo? ¿Precision? ¿Ultima calibracion? ¿Retrasos?",
        },
        {
            "ID_Tecnico": "1FSRFTB504",
            "Nombre_amigable": "flujo_vapor_sobrecalentado",
            "Descripcion_funcional": "Caudal de vapor que incide en la turbina - Variable critica para SPE",
            "Unidad": "t/h",
            "Tipo_dato": "float",
            "Tipo_en_modelo": "Carga",
            "Tipo_variable": "Flujo",
            "Mecanismos_asociados": "SPE (Solid Particle Erosion)",
            "Ecuacion": "sigma_y = 1.14e-7 * rho_ox * d_ox^3 * (F_v/S)^2 - Ecs (2.1),(2.11),(2.15),(2.16),(2.17)",
            "Rol_en_ecuacion": "F_v en energia cinetica para erosion SPE. rho_ox=5.08 g/cm³, d_ox via oxidacion parabolica. Constantes: A=6.22e20 µm²/h, Eox=-326kJ/mol. Referencia: Perez (2024), Reshetnyak (1995)",
            "Rango_min": 774.38,
            "Rango_max": 788.41,
            "Distribucion_observada": "Weibull (forma=321.4, escala=785.4), asimetrica positiva, colas largas, KS p-value=0.98",
            "Pregunta_planta": "¿Ubicacion? ¿Directa o calculada? ¿Frecuencia? ¿Precision? ¿Calibracion? ¿Retrasos de transporte?",
        },
        {
            "ID_Tecnico": "1FSRTE502C",
            "Nombre_amigable": "temp_vapor_sobrecalentado_atemperador",
            "Descripcion_funcional": "Temperatura del vapor despues del atemperador - Variable para transferencia de calor",
            "Unidad": "°C",
            "Tipo_dato": "float",
            "Tipo_en_modelo": "Carga",
            "Tipo_variable": "Temperatura",
            "Mecanismos_asociados": "Choque_termico,Fatiga_termica",
            "Ecuacion": "Nu = 0.023 * Re^0.8 * Pr^n (Dittus-Boelter) - Ecs (2.25),(2.27),(2.28)",
            "Rol_en_ecuacion": "T entrada para coeficiente de pelicula y numero de Nusselt. n=0.4 calentamiento, n=0.02 calentamiento real. Referencia: Perez (2024), Leyzerovich (2008)",
            "Rango_min": 401.19,
            "Rango_max": 403.35,
            "Distribucion_observada": "Weibull (forma=685.8, escala=402.6), asimetrica positiva, colas cortas, KS p-value=0.34",
            "Pregunta_planta": "¿Ubicacion? ¿Contacto directo? ¿Frecuencia? ¿Precision? ¿Calibracion? ¿Retraso termico?",
        },
        {
            "ID_Tecnico": "1FRSTE503A",
            "Nombre_amigable": "temp_vapor_recalentado_salida",
            "Descripcion_funcional": "Temperatura del vapor recalentado a salida de caldera - Variable critica para Creep",
            "Unidad": "°C",
            "Tipo_dato": "float",
            "Tipo_en_modelo": "Carga",
            "Tipo_variable": "Temperatura",
            "Mecanismos_asociados": "Creep (Fluencia lenta),Fatiga_termica",
            "Ecuacion": "LMP = T*(C + log10(t_r)) - Ecs (2.8),(2.9),(2.12),(2.32)",
            "Rol_en_ecuacion": "T absoluta para parametro Larson-Miller, C=20, en vida remanente por creep. Influye en oxidacion parabolica. Referencia: Perez (2024), Mendelson (1965)",
            "Rango_min": 535.14,
            "Rango_max": 538.88,
            "Distribucion_observada": "Weibull (forma=479.2, escala=537.6), asimetrica positiva, colas cortas, KS p-value=0.48",
            "Pregunta_planta": "¿Ubicacion? ¿Directa? ¿Frecuencia? ¿Precision? ¿Calibracion? ¿Influencia de radiacion?",
        },
        {
            "ID_Tecnico": "1FSRPT501",
            "Nombre_amigable": "presion_domo",
            "Descripcion_funcional": "Presion del domo de la caldera - Variable para esfuerzo circunferencial",
            "Unidad": "bar",
            "Tipo_dato": "float",
            "Tipo_en_modelo": "Carga",
            "Tipo_variable": "Presion",
            "Mecanismos_asociados": "Creep,SCC (Stress Corrosion Cracking)",
            "Ecuacion": "sigma_theta = P*r/t (esfuerzo circunferencial)",
            "Rol_en_ecuacion": "P genera esfuerzos de membrana en paredes del domo para analisis de creep y SCC. sigma_theta = P*r/t. Referencia: Perez (2024)",
            "Rango_min": 171.45,
            "Rango_max": 174.16,
            "Distribucion_observada": "Normal (mu=173.2, sigma=0.62), simetrica, colas cortas, KS p-value=0.94",
            "Pregunta_planta": "¿Ubicacion? ¿Directa? ¿Frecuencia? ¿Precision? ¿Calibracion? ¿Pulsaciones?",
        },
        {
            "ID_Tecnico": "1FSRPT504",
            "Nombre_amigable": "presion_vapor_sobrecalentado_turbina",
            "Descripcion_funcional": "Presion del vapor sobrecalentado a entrada de turbina - Variable para SPE y densidad",
            "Unidad": "bar",
            "Tipo_dato": "float",
            "Tipo_en_modelo": "Carga",
            "Tipo_variable": "Presion",
            "Mecanismos_asociados": "SPE,Creep",
            "Ecuacion": "V = F_v/S, rho_corregida = f(P,T) - Ecs (2.14),(2.19)",
            "Rol_en_ecuacion": "P_tr entrada para correccion de densidad del vapor y calculo de velocidad V = F_v/S. Influye en energia cinetica de SPE. Referencia: Perez (2024)",
            "Rango_min": 164.26,
            "Rango_max": 166.80,
            "Distribucion_observada": "Gamma (forma=78396, escala=0.002), asimetrica positiva, colas cortas, KS p-value=0.96",
            "Pregunta_planta": "¿Ubicacion? ¿Directa? ¿Frecuencia? ¿Precision? ¿Calibracion? ¿Vibraciones?",
        },
        {
            "ID_Tecnico": "1FRSPT526",
            "Nombre_amigable": "presion_vapor_entrada_recalentador",
            "Descripcion_funcional": "Presion del vapor antes del recalentamiento - Variable para oxidacion parabolica",
            "Unidad": "bar",
            "Tipo_dato": "float",
            "Tipo_en_modelo": "Carga",
            "Tipo_variable": "Presion",
            "Mecanismos_asociados": "Creep,Oxidacion",
            "Ecuacion": "d_ox^2 = 2*A*exp(-Eox/(R*T))*dt - Ecs (2.10),(2.36),(2.37),(2.38)",
            "Rol_en_ecuacion": "P_T entrada para calculo de espesor de oxido d_ox via oxidacion parabolica. Constantes: A=6.22e20 µm²/h, Eox=-326kJ/mol. Influye en sigma_y para SPE. Referencia: Sabau (2014), Perez (2024)",
            "Rango_min": 29.51,
            "Rango_max": 30.38,
            "Distribucion_observada": "Gamma (forma=10723, escala=0.003), asimetrica positiva, colas cortas, KS p-value=0.71",
            "Pregunta_planta": "¿Ubicacion? ¿Directa? ¿Frecuencia? ¿Precision? ¿Calibracion? ¿Humedad?",
        },
        {
            "ID_Tecnico": "Acero_1CrMoV_LimFluencia",
            "Nombre_amigable": "limite_fluencia_acero_rotor",
            "Descripcion_funcional": "Limite de fluencia del acero 1CrMoV (240 MPa segun Perez 2024). Composicion: C=0.28-0.35%, Cr=0.90-1.20%, Mo=0.20-0.35%, V=0.05-0.15%",
            "Unidad": "MPa",
            "Tipo_dato": "float",
            "Tipo_en_modelo": "Resistencia",
            "Tipo_variable": "Propiedad_mecanica",
            "Mecanismos_asociados": "SPE,Creep,Fatiga_termica,SCC",
            "Ecuacion": "sigma_y_resistencia = sigma_y (Perez 2024)",
            "Rol_en_ecuacion": "sigma_y=240 MPa resistencia superficial contra erosion SPE. Composicion segun ASTM A470. Tratamiento: Austenizacion 850-900C, Revenido 540-680C. Referencia: Perez (2024), ASM Handbook",
            "Rango_min": 240.0,
            "Rango_max": 240.0,
            "Distribucion_observada": "Normal",
            "Pregunta_planta": "Composicion: C=0.28-0.35%, Cr=0.90-1.20%, Mo=0.20-0.35%, V=0.05-0.15%. Trat: Austeniz 850-900C + Revenido 540-680C. Certificados: ASTM A470, ASME Section II. Ubicacion probetas: zona rotor, eje",
        },
        {
            "ID_Tecnico": "Acero_1CrMoV_ResFatiga",
            "Nombre_amigable": "resistencia_fatiga_acero",
            "Descripcion_funcional": "Resistencia a fatiga corregida del acero 1CrMoV (190 MPa - Anexo 6 tesis). Curva S-N: sigma = 1315 - 0.563*N",
            "Unidad": "MPa",
            "Tipo_dato": "float",
            "Tipo_en_modelo": "Resistencia",
            "Tipo_variable": "Propiedad_mecanica",
            "Mecanismos_asociados": "Fatiga_termica,Vibraciones_mecanicas",
            "Ecuacion": "sigma_n = Ca*Cb*Cc*Cd*Ce*sigma_n_prim (Anexo 6)",
            "Rol_en_ecuacion": "Resistencia a fatiga corregida. Coeficientes: Ca=0.75 (superficial), Cb=0.85 (tamano eje 550mm), Cc=0.82 (confianza 99%), Cd=0.42 (T=540C), Ce=0.99 (entalla). sigma_n_prim=835 MPa teorica. Curva S-N: sigma = 1315 - 0.563*N. Referencia: Anexo 6 tesis, ASM Fatigue Handbook",
            "Rango_min": 190.0,
            "Rango_max": 190.0,
            "Distribucion_observada": "Normal",
            "Pregunta_planta": "Coeficientes: Ca=0.75, Cb=0.85, Cc=0.82, Cd=0.42, Ce=0.99. Curva S-N: sigma=1315-0.563N. Temp. operacion: 530C (800K). Zona probetas: rotor, eje. Norma: ASTM E466",
        },
        {
            "ID_Tecnico": "Acero_1CrMoV_ModElasticidad",
            "Nombre_amigable": "modulo_elasticidad_acero",
            "Descripcion_funcional": "Modulo de Young del acero 1CrMoV (160 GPa segun Perez 2024). Degrada >450C",
            "Unidad": "GPa",
            "Tipo_dato": "float",
            "Tipo_en_modelo": "Resistencia",
            "Tipo_variable": "Propiedad_mecanica",
            "Mecanismos_asociados": "Vibraciones_mecanicas,Fatiga_termica",
            "Ecuacion": "sigma = E*epsilon (Ley elastica de Hooke)",
            "Rol_en_ecuacion": "Modulo de Young E=160 GPa para calculo de deformaciones elasticas. Degrada >450C. Referencia: Perez (2024), ASM Handbook",
            "Rango_min": 160.0,
            "Rango_max": 160.0,
            "Distribucion_observada": "Normal",
            "Pregunta_planta": "E=160 GPa a temp. ambiente. Curva E vs T: degradacion >450C. Ensayo a temp. elevada necesario. Tipo: 1CrMoV. Precision: segun ASTM A470",
        },
        {
            "ID_Tecnico": "Acero_1CrMoV_DilTermica",
            "Nombre_amigable": "coef_dilatacion_termica",
            "Descripcion_funcional": "Coeficiente de dilatacion termica del acero 1CrMoV (1.2x10^-5 1/°C). Critico para choque termico",
            "Unidad": "1/°C",
            "Tipo_dato": "float",
            "Tipo_en_modelo": "Resistencia",
            "Tipo_variable": "Propiedad_termica",
            "Mecanismos_asociados": "Choque_termico,Fatiga_termica",
            "Ecuacion": "delta_L = alpha * L0 * delta_T",
            "Rol_en_ecuacion": "Coeficiente alpha=1.2e-5 1/°C para calculo de deformaciones termicas. Referencia: Pagina 103 tesis",
            "Rango_min": 1.2e-5,
            "Rango_max": 1.2e-5,
            "Distribucion_observada": "Normal",
            "Pregunta_planta": "Alpha=1.2e-5 1/°C. Ensayo a temp. elevada requerido (>450C). Tipo: 1CrMoV. Precision: segun ASTM A470",
        },
        {
            "ID_Tecnico": "Acero_1CrMoV_Densidad",
            "Nombre_amigable": "densidad_acero",
            "Descripcion_funcional": "Densidad del acero 1CrMoV (7.8 g/cm³). Tipica de aceros CrMoV",
            "Unidad": "g/cm³",
            "Tipo_dato": "float",
            "Tipo_en_modelo": "Resistencia",
            "Tipo_variable": "Propiedad_masica",
            "Mecanismos_asociados": "SPE,Vibraciones_mecanicas",
            "Ecuacion": "masa = densidad * volumen",
            "Rol_en_ecuacion": "Densidad=7.8 g/cm³ para calculo de masa y esfuerzos inerciales. Referencia: Pagina 103 tesis",
            "Rango_min": 7.8,
            "Rango_max": 7.8,
            "Distribucion_observada": "Normal",
            "Pregunta_planta": "Densidad=7.8 g/cm³ segun ASM Handbook. Ensayo: metodo hidrostatico. Muestra: representativa del rotor. Homogeneidad verificada por certificados ASTM A470",
        },
        {
            "ID_Tecnico": "Acero_1CrMoV_Cp",
            "Nombre_amigable": "capacidad_calorifica",
            "Descripcion_funcional": "Capacidad calorifica del acero 1CrMoV (680 J/kg°C). Degrada >500C",
            "Unidad": "J/kg°C",
            "Tipo_dato": "float",
            "Tipo_en_modelo": "Resistencia",
            "Tipo_variable": "Propiedad_termica",
            "Mecanismos_asociados": "Choque_termico,Fatiga_termica,Creep",
            "Ecuacion": "Q = Cp * masa * delta_T",
            "Rol_en_ecuacion": "Capacidad calorifica Cp=680 J/kg°C para transferencia de calor. Degrada >500C. Referencia: Pagina 103 tesis",
            "Rango_min": 680.0,
            "Rango_max": 680.0,
            "Distribucion_observada": "Normal",
            "Pregunta_planta": "Cp=680 J/kg°C a temp. ambiente. Curva Cp vs T: degradacion >500C. Ensayo: calorimeria diferencial. Norma: ASTM E1269",
        },
        {
            "ID_Tecnico": "Oxido_Fe3O4_Densidad",
            "Nombre_amigable": "densidad_oxido_magnetita",
            "Descripcion_funcional": "Densidad del oxido magnetita (Fe3O4) - 5.08 g/cm³. Transforma a hematites >600C",
            "Unidad": "g/cm³",
            "Tipo_dato": "float",
            "Tipo_en_modelo": "Resistencia",
            "Tipo_variable": "Propiedad_oxido",
            "Mecanismos_asociados": "SPE",
            "Ecuacion": "sigma_y = 1.14e-7 * rho_ox * d_ox^3 * (F_v/S)^2",
            "Rol_en_ecuacion": "Densidad oxidos rho_ox=5.08 g/cm³ para erosion SPE. Transforma a hematites >600C. Referencia: Sabau (2014), Dooley (2019)",
            "Rango_min": 5.08,
            "Rango_max": 5.08,
            "Distribucion_observada": "Normal",
            "Pregunta_planta": "¿Composicion exacta? ¿Oxidacion? ¿Espesor escama?",
        },
    ]

    return pd.DataFrame(datos)
