import pandas as pd


def cargar_variables_prototipo():
    """Carga el catalogo prototipo de variables SCADA y propiedades de materiales."""

    datos = [
        {
            "ID_Tecnico": "1GEV007CE",
            "Nombre_amigable": "potencia_activa",
            "Descripcion_funcional": "Nivel de exigencia operativa del sistema",
            "Unidad": "MW",
            "Tipo_dato": "float",
            "Tipo_en_modelo": "Carga",
            "Tipo_variable": "Potencia",
            "Mecanismos_asociados": "Vibraciones_mecanicas",
            "Ecuacion": "Cap.2",
            "Rol_en_ecuacion": "Potencia de salida que induce esfuerzos mecanicos y vibraciones en el rotor",
            "Rango_min": 263.56,
            "Rango_max": 272.11,
            "Distribucion_observada": "Multimodal, simetrica, colas cortas",
            "Pregunta_planta": "¿Ubicacion del sensor? ¿Medicion directa o calculada? ¿Frecuencia de muestreo? ¿Precision? ¿Ultima calibracion? ¿Retrasos?"
        },
        {
            "ID_Tecnico": "1FSRFTB504",
            "Nombre_amigable": "flujo_vapor_sobrecalentado",
            "Descripcion_funcional": "Caudal de vapor que incide en la turbina",
            "Unidad": "t/h",
            "Tipo_dato": "float",
            "Tipo_en_modelo": "Carga",
            "Tipo_variable": "Flujo",
            "Mecanismos_asociados": "SPE,Choque_termico,Fatiga_termica",
            "Ecuacion": "(2.1),(2.11),(2.16),(2.17)",
            "Rol_en_ecuacion": "F_v en energia cinetica (Ec=1/2*rho*d_ox^3*F_v/S^2) y velocidad del vapor",
            "Rango_min": 774.38,
            "Rango_max": 788.41,
            "Distribucion_observada": "Multimodal, asimetrica negativa, colas largas",
            "Pregunta_planta": "¿Ubicacion? ¿Directa o calculada? ¿Frecuencia? ¿Precision? ¿Calibracion? ¿Retrasos de transporte?"
        },
        {
            "ID_Tecnico": "1FSRTE502C",
            "Nombre_amigable": "temp_vapor_sobrecalentado_atemperador",
            "Descripcion_funcional": "Temperatura del vapor despues del atemperador",
            "Unidad": "°C",
            "Tipo_dato": "float",
            "Tipo_en_modelo": "Carga",
            "Tipo_variable": "Temperatura",
            "Mecanismos_asociados": "Choque_termico,Fatiga_termica",
            "Ecuacion": "Cap.2 - Transferencia de calor",
            "Rol_en_ecuacion": "T determina esfuerzos termicos y numero de Nusselt",
            "Rango_min": 401.19,
            "Rango_max": 403.35,
            "Distribucion_observada": "Multimodal, simetrica, colas cortas",
            "Pregunta_planta": "¿Ubicacion? ¿Contacto directo? ¿Frecuencia? ¿Precision? ¿Calibracion? ¿Retraso termico?"
        },
        {
            "ID_Tecnico": "1FRSTE503A",
            "Nombre_amigable": "temp_vapor_recalentado_salida",
            "Descripcion_funcional": "Temperatura del vapor recalentado a salida de caldera",
            "Unidad": "°C",
            "Tipo_dato": "float",
            "Tipo_en_modelo": "Carga",
            "Tipo_variable": "Temperatura",
            "Mecanismos_asociados": "Creep,Fatiga_termica,SPE",
            "Ecuacion": "(2.8),(2.9),(2.12)",
            "Rol_en_ecuacion": "T afecta espesor de oxido y parametro de Larson-Miller",
            "Rango_min": 535.14,
            "Rango_max": 538.88,
            "Distribucion_observada": "Multimodal, simetrica, colas cortas",
            "Pregunta_planta": "¿Ubicacion? ¿Directa? ¿Frecuencia? ¿Precision? ¿Calibracion? ¿Influencia de radiacion?"
        },
        {
            "ID_Tecnico": "1FSRPT501",
            "Nombre_amigable": "presion_domo",
            "Descripcion_funcional": "Presion del domo de la caldera",
            "Unidad": "bar",
            "Tipo_dato": "float",
            "Tipo_en_modelo": "Carga",
            "Tipo_variable": "Presion",
            "Mecanismos_asociados": "Creep,SCC",
            "Ecuacion": "Cap.2 - Esfuerzo circunferencial",
            "Rol_en_ecuacion": "P genera esfuerzos de membrana sigma_theta = P*r/t",
            "Rango_min": 171.45,
            "Rango_max": 174.16,
            "Distribucion_observada": "Multimodal, asimetrica negativa, colas largas",
            "Pregunta_planta": "¿Ubicacion? ¿Directa? ¿Frecuencia? ¿Precision? ¿Calibracion? ¿Pulsaciones?"
        },
        {
            "ID_Tecnico": "1FSRPT504",
            "Nombre_amigable": "presion_vapor_sobrecalentado_turbina",
            "Descripcion_funcional": "Presion del vapor sobrecalentado a entrada de turbina",
            "Unidad": "bar",
            "Tipo_dato": "float",
            "Tipo_en_modelo": "Carga",
            "Tipo_variable": "Presion",
            "Mecanismos_asociados": "SPE,Creep",
            "Ecuacion": "(2.14),(2.19)",
            "Rol_en_ecuacion": "P_tr para correccion de densidad y calculo de velocidad",
            "Rango_min": 165.28,
            "Rango_max": 166.80,
            "Distribucion_observada": "Multimodal, asimetrica negativa, colas largas",
            "Pregunta_planta": "¿Ubicacion? ¿Directa? ¿Frecuencia? ¿Precision? ¿Calibracion? ¿Vibraciones?"
        },
        {
            "ID_Tecnico": "1FRSPT526",
            "Nombre_amigable": "presion_vapor_entrada_recalentador",
            "Descripcion_funcional": "Presion del vapor antes del recalentamiento",
            "Unidad": "bar",
            "Tipo_dato": "float",
            "Tipo_en_modelo": "Carga",
            "Tipo_variable": "Presion",
            "Mecanismos_asociados": "Creep,Fatiga",
            "Ecuacion": "(2.10)",
            "Rol_en_ecuacion": "P_T en calculo de espesor de oxido d_ox^2 = 2*alpha^3*P_T^2*dt",
            "Rango_min": 29.51,
            "Rango_max": 30.38,
            "Distribucion_observada": "Multimodal, simetrica, colas cortas",
            "Pregunta_planta": "¿Ubicacion? ¿Directa? ¿Frecuencia? ¿Precision? ¿Calibracion? ¿Humedad?"
        },
        {
            "ID_Tecnico": "Acero_CrMoV_LimFluencia",
            "Nombre_amigable": "limite_fluencia_acero_rotor",
            "Descripcion_funcional": "Limite de fluencia del acero CrMoV del rotor",
            "Unidad": "MPa",
            "Tipo_dato": "float",
            "Tipo_en_modelo": "Resistencia",
            "Tipo_variable": "Propiedad_mecanica",
            "Mecanismos_asociados": "SPE,Creep,Fatiga_termica,SCC",
            "Ecuacion": "(2.6),(2.11),(2.12)",
            "Rol_en_ecuacion": "sigma_y resistencia superficial contra erosion. sigma_y = Hv/3",
            "Rango_min": 350.0,
            "Rango_max": 450.0,
            "Distribucion_observada": "Normal",
            "Pregunta_planta": "¿Composicion exacta? ¿Tratamiento termico? ¿Certificados? ¿Ensayos? ¿Precision de ensayos? ¿Calibracion de equipos? ¿Ubicacion de probetas?"
        },
        {
            "ID_Tecnico": "Acero_CrMoV_ResFatiga",
            "Nombre_amigable": "resistencia_fatiga_acero",
            "Descripcion_funcional": "Resistencia a fatiga corregida del acero",
            "Unidad": "MPa",
            "Tipo_dato": "float",
            "Tipo_en_modelo": "Resistencia",
            "Tipo_variable": "Propiedad_mecanica",
            "Mecanismos_asociados": "Fatiga_termica,Vibraciones_mecanicas",
            "Ecuacion": "sigma_n = Ca*Cb*Cc*Cd*Ce*sigma_n",
            "Rol_en_ecuacion": "Resistencia a fatiga corregida por coeficientes de superficie, tamanio, confiabilidad, temperatura y entalla",
            "Rango_min": 150.0,
            "Rango_max": 230.0,
            "Distribucion_observada": "Normal",
            "Pregunta_planta": "¿Valores de coeficientes? ¿Curvas S-N? ¿Temp. operacion? ¿Precision de ensayos? ¿Calibracion? ¿Ubicacion de probetas?"
        },
        {
            "ID_Tecnico": "Acero_CrMoV_ModElasticidad",
            "Nombre_amigable": "modulo_elasticidad_acero",
            "Descripcion_funcional": "Modulo de Young del acero",
            "Unidad": "GPa",
            "Tipo_dato": "float",
            "Tipo_en_modelo": "Resistencia",
            "Tipo_variable": "Propiedad_mecanica",
            "Mecanismos_asociados": "Vibraciones_mecanicas,Fatiga_termica",
            "Ecuacion": "sigma = E*epsilon",
            "Rol_en_ecuacion": "Modulo de Young E para calculo de deformaciones elasticas",
            "Rango_min": 190.0,
            "Rango_max": 210.0,
            "Distribucion_observada": "Normal",
            "Pregunta_planta": "¿Valor de E a temp. operacion? ¿Curva E vs T? ¿Ensayo a temp. elevada? ¿Tipo acero? ¿Precision? ¿Calibracion? ¿Ubicacion?"
        }
    ]

    return pd.DataFrame(datos)
